"""empty message

Revision ID: 711cfb9b2243
Revises: 2da116fbef09
Create Date: 2018-08-31 00:52:30.124790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '711cfb9b2243'
down_revision = '2da116fbef09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'updated_at')
    # ### end Alembic commands ###
